apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-esqh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-revx-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-esqh@sha256:97803809555b0332ad4c30af2514132ac9b78340d30c5604f5daa2dbcd60f439
        name: my-nodejs
        resources: {}
status: {}
